modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="createtweaker"
version="${file.jarVersion}"
displayName="CreateTweaker"
updateJSONURL="https://updates.blamejared.com/get?n=createtweaker&gv=1.20.1"
authors="Jaredlll08"
logoFile="icon.png"
description='''
Adds CraftTweaker support to Create
'''

[[dependencies.createtweaker]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.createtweaker]]
modId = "crafttweaker"
mandatory = true
versionRange = "[14.0.16,)"
ordering = "NONE"
side = "BOTH"