modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="createtweaker" #mandatory
version="${file.jarVersion}" #mandatory
displayName="CreateTweaker" #mandatory
updateJSONURL="https://updates.blamejared.com/get?n=createtweaker&gv=1.16.5" #optional
authors="Jaredlll08" #optional
description='''
Adds CraftTweaker support to Create
'''

[[dependencies.createtweaker]]
modId = "create"
mandatory = true
versionRange = "[v0.3.2f,v0.3.2g)"
ordering = "NONE"
side = "BOTH"
[[dependencies.createtweaker]]
modId = "crafttweaker"
mandatory = true
versionRange = "[7.1,)"
ordering = "NONE"
side = "BOTH"